update for gnome 42 compatibility
ethanwharris/gnome-nvidia-extension pull request #201
Opened 2022-04-15 14:05 UTC by derenv

Update metadata.json to allow Gnome 42 compatibility, also sets version to v9.1

Related to #199

2022-04-17 14:11 UTC, kenohassler commented
Hi Deren, happy Easter 😃
I agree we should have this hotfix!
However, as per the review guidelines, only integer version numbers are allowed (https://gjs.guide/extensions/review-guidelines/review-guidelines.html#metadata-json-must-be-well-formed). So I think we have two options here: keep version 9, move the GitHub v9 tag a few commits and re-submit. Or, bump to v10 so we don't have to move the tag. Anyway, I'll test the extension on a clean Ubuntu 22.04 in the following days and let you know if I spot any issues 🙂

2022-04-17 14:12 UTC, kenohassler requested changes
Integer version number 🤓

2022-04-21 14:31 UTC, derenv commented on src/nvidiautil@ethanwharris/metadata.json
> +  "version": 10
not sure if this should be 9 or 10, as v9 was rejected.

2022-04-21 14:50 UTC, kenohassler approved these changes

2022-04-21 16:28 UTC, merged